// OTOMATİK ÜRETİLDİ — scripts/gen-modules.mjs. Elle düzenlemeyin.
import type { ModuleDef } from './modules'
import m0 from '../modules/academic/module'
import m1 from '../modules/attendance/module'
import m2 from '../modules/calendar/module'
import m3 from '../modules/classroom-design/module'
import m4 from '../modules/coaching/module'
import m5 from '../modules/communication/module'
import m6 from '../modules/core/module'
import m7 from '../modules/crm/module'
import m8 from '../modules/desktop-apps/module'
import m9 from '../modules/discipline/module'
import m10 from '../modules/exams/module'
import m11 from '../modules/finance/module'
import m12 from '../modules/guidance/module'
import m13 from '../modules/integrations/module'
import m14 from '../modules/placement/module'
import m15 from '../modules/portal/module'
import m16 from '../modules/reports/module'
import m17 from '../modules/settings/module'
import m18 from '../modules/staff/module'
import m19 from '../modules/students/module'
import m20 from '../modules/sync/module'
import m21 from '../modules/teacher-portal/module'

export const loadedModules: ModuleDef[] = [m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20, m21]
